sudo: false
language: node_js
matrix:
  include:
    - node_js: "8"

dist: trusty
# Make chrome browser available for testing
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

cache:
  directories:
    - node_modules

after_script:
  - npm run build
  - npm run test:size
  - npm run deploy
# Necessary to compile native modules for io.js v3 or Node.js v4
env:
  - CXX=g++-4.8

# Necessary to compile native modules for io.js v3 or Node.js v4
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
